language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#travis"
deploy:
   skip_cleanup: true
   provider: bluemixcloudfoundry
   username: vivek_bajpai@persistent.co.in
   password: Cisco@231
   organization: vivek_persistent
   space: NodeTest
   manifest: manifest-prod.yml
   on:
    branch: master
  
